version: '3.8'

services:

  wordpress:
    # build:
    #   context: ./wordpress
    platform: linux/x86_64
    image: spidicey/word-press-docker:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 270701
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html


  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 270701
    volumes:
      - mysql_data:/var/lib/mysql


 
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
  mysql_data:

